### ISSUE TITLE
these devices SUCK!

### ISSUE THREAD

**Issue by beaudamore** [os-js/OS.js#627] opened 2017-08-06 20:09 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://beauduino.local/packages/target/ArduinoPackageManager/combined.js?41608:282:28
    at ArduinoHandler.<anonymous> (http://beauduino.local/packages/target/ArduinoPackageManager/combined.js?41608:254:16)
    at ArduinoHandler.<anonymous> (http://beauduino.local/osjs.js:1692:14)
    at Object.onerror (http://beauduino.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://beauduino.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment] 2017-08-06 20:17
Hi,

Try using Luci instead: `http://<your-board-ip>/cgi-bin/luci` as that is an alternative utility to help set up the Arduino.

Please note that this repo is just for the sources of some software Arduino uses, so if you have trouble with the device you have to contact them.

Marking as duplicate of: #436

**Closed by andersevenrud** 2017-08-06 20:17 UTC
