### ISSUE TITLE
Memory Usage of Osjs Components

### ISSUE THREAD

**Issue by mahsashadi** [os-js/OS.js#751] opened 2020-09-22 12:31 UTC
Hi, I am monitoring the memory usage of my developed widget on osjs. 
Part of its memory is unallocated when the target widget is removed and then re-created, and the rest remains allocated. This behaviour is the same for other osjs components like Draw tool and File manager, as I attached their diagrams, using memory timeline of chrome Devtools. I have the following questions:

1. Why memory is not unallocated immediately after removing widget or closing the component
2. Why some parts still remain allocated even after removing and then re-creating

![c](https://user-images.githubusercontent.com/70196035/93882018-7c882500-fcec-11ea-908b-8fb80ae72bc4.png)

**Comment by andersevenrud** [comment] 2020-09-22 14:25
Remember that JavaScript is a garbage collected language, so in many cases you won't see an instant de-allocation.

As for why some is not collected, these are the usual causes:

* Elements not being removed from DOM
* DOM Element references are not nulled on destructors
* setInterval/setTimeout etc. was not cleared

**Comment by andersevenrud** [comment] 2020-09-22 21:40
FYI: I made a new release of `@osjs/client` containing this change that might help clear up some minor stuff: https://github.com/os-js/osjs-client/commit/815daad7cad41b0de297ac7e1bfd328c7b5456eb

Also made another release of `@osjs/widget` that does some additional cleanup (I saw that for canvas rendered widgets the context was not unset). Probably won't affect the results you've benchmarked though. As far as I can see there's no memory leaks or whatever.

Another thing is, that I can't reproduce your graphs, because I don't have this profiler tab available in my devtools for some reason. Not sure what's up with that yet.

**Comment by mahsashadi** [comment] 2020-09-23 08:35
Thanks for your reply. Your new releases don't affect the pattern seen in my graphs. However, as you said, there is no serious memory leaks in that.

**Comment by andersevenrud** [comment] 2020-09-23 17:58
I've done a bit of debugging on this and from what I can see everything related to DOM in the client is cleaned up appropriately. The heap snapshots at least does not show any yellow detached nodes.

Also seems like the `Window` and `Application` instances are properly GC-ed after they are destroyed and de-referenced.

Going to have another look this weekend to see if there's room for improvement in other areas.

**Comment by andersevenrud** [comment] 2020-10-04 20:11
I can't seem to find any specific point in the code to improve memory usage any further, so I'm closing this issue.

If you hit any problems relating to this in the future, feel free to re-open this issue.

**Closed by andersevenrud** 2020-10-04 20:11 UTC
