### ISSUE TITLE
OS.js cannot find manifest data for generated application

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/OS.js#630] opened 2017-08-17 20:22 UTC
## Expected behaviour
To load the application

## Actual behaviour
Error: Failed to launch 'Java'. Application manifest data not found!
    at r (https://osjs-spaceboyross.c9users.io/osjs.js:31:84163)
    at https://osjs-spaceboyross.c9users.io/osjs.js:31:85901
    at o.e._execute (https://osjs-spaceboyross.c9users.io/common.js:55:19146)
    at o._resolveFromExecutor (https://osjs-spaceboyross.c9users.io/common.js:55:45637)
    at new o (https://osjs-spaceboyross.c9users.io/common.js:55:37863)
    at Function.value (https://osjs-spaceboyross.c9users.io/osjs.js:31:85646)
    at https://osjs-spaceboyross.c9users.io/osjs.js:31:86171
    at o.e._execute (https://osjs-spaceboyross.c9users.io/common.js:55:19146)
    at o._resolveFromExecutor (https://osjs-spaceboyross.c9users.io/common.js:55:45637)
    at new o (https://osjs-spaceboyross.c9users.io/common.js:55:37863)
    at https://osjs-spaceboyross.c9users.io/osjs.js:31:86120
    at o (https://osjs-spaceboyross.c9users.io/common.js:55:72474)
    at Object.l (https://osjs-spaceboyross.c9users.io/common.js:55:59756)
    at Object.f (https://osjs-spaceboyross.c9users.io/common.js:55:59637)
    at Object.o (https://osjs-spaceboyross.c9users.io/common.js:55:72474)
    at o._settlePromiseFromHandler (https://osjs-spaceboyross.c9users.io/common.js:55:46040)

## Steps to reproduce the error
Install the java program from https://github.com/Ross-Software/OSjs-repository/raw/master/packages.json

**Comment by andersevenrud** [comment] 2017-08-17 20:29
Did you see my reply here ?
https://github.com/os-js/OS.js-submissions/issues/2#issuecomment-322878254

**Comment by andersevenrud** [comment] 2017-08-17 20:31
Also, does your `className` in metadata match up with the `OSjs.Applications.<something> = ...` ?

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:31
It starts now and the className maches

**Comment by andersevenrud** [comment] 2017-08-17 20:32
So... there is nothing wrong ? Usually this is a symptom of:

1. `node osjs build:manifest` was not run
2. `className` is not properly defined
3. Trying to launch with wrong name

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:33
After running `node osjs build:mainifest`, I got:
```
Error: Failed to launch 'Java'. Application manifest data not found!
    at r (https://osjs-spaceboyross.c9users.io/osjs.js:31:84163)
    at https://osjs-spaceboyross.c9users.io/osjs.js:31:85901
    at o.e._execute (https://osjs-spaceboyross.c9users.io/common.js:55:19146)
    at o._resolveFromExecutor (https://osjs-spaceboyross.c9users.io/common.js:55:45637)
    at new o (https://osjs-spaceboyross.c9users.io/common.js:55:37863)
    at Function.value (https://osjs-spaceboyross.c9users.io/osjs.js:31:85646)
    at https://osjs-spaceboyross.c9users.io/osjs.js:31:86171
    at o.e._execute (https://osjs-spaceboyross.c9users.io/common.js:55:19146)
    at o._resolveFromExecutor (https://osjs-spaceboyross.c9users.io/common.js:55:45637)
    at new o (https://osjs-spaceboyross.c9users.io/common.js:55:37863)
    at https://osjs-spaceboyross.c9users.io/osjs.js:31:86120
    at o (https://osjs-spaceboyross.c9users.io/common.js:55:72474)
    at Object.l (https://osjs-spaceboyross.c9users.io/common.js:55:59756)
    at Object.f (https://osjs-spaceboyross.c9users.io/common.js:55:59637)
    at Object.o (https://osjs-spaceboyross.c9users.io/common.js:55:72474)
    at o._settlePromiseFromHandler (https://osjs-spaceboyross.c9users.io/common.js:55:46040)
```

**Comment by andersevenrud** [comment] 2017-08-17 20:35
Well, you want to launch `ApplicationJava` and not `Java` it seems as I look at your code.

Btw, compile with `--debug` to get a better stacktrace.

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:38
Now ApplicationJava does not exists in OSjs.Applications

**Comment by andersevenrud** [comment] 2017-08-17 20:39
It does not appear in `OSjs.Applications` before it is launched.

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:41
I've found that loading the OS.js java library when the window shows is better than when the app starts

**Comment by andersevenrud** [comment] 2017-08-17 20:43
I cloned your repository and it launches just fine for me on `master`. Does this happen when you restore the user session ? In that case, maybe you renamed the app or something and it tries to launch the wrong thing ?

> I've found that loading the OS.js java library when the window shows is better than when the app starts

Ideally you want to use `require` or `import` in your main file so it gets compiled with Webpack. This way you don't have to do another request. But not all libraries support this out of the box (AMD/requirejs/browserify).

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:45
I forgot to load the javapoly library

**Comment by andersevenrud** [comment] 2017-08-17 20:47
This still does not answer the question: Is there still something wrong or has it been fixed on your side ?

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:48
no

**Comment by andersevenrud** [comment] 2017-08-17 20:49
No as in "there's nothing wrong" or "not fixed" ?

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:50
no fixed

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:51
I still get the error dialog on start

**Comment by andersevenrud** [comment] 2017-08-17 20:52
I cannot reproduce this problem myself, so I don't know how to help.

I did this:

1. `mkdir src/packages/ross`
2. `git clone https://github.com/Ross-Software/OSjs-repository.git src/packages/ross`
3. `node osjs config:add --name=repositories --value=ross
4. `node osjs build:manifest`
5. `node osjs build:package --name=ross/Java`

And then launched it via the menu. A window shows up with nothing in it.

**Comment by andersevenrud** [comment] 2017-08-17 20:53
Have you tried restarting the server and client ? Maybe something was cached ?!

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:55
Steps:

1. `cd src/packages`
2. `git clone https://github.com/Ross-Software/OSjs-repository.git rosssoftware`
3. `cd ../..`
4. `node osjs config:add --name=repositories --value=rosssoftware`
5. `node osjs build:manifest`
6. `node osjs build:package --name=rosssoftware/Java`

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:56
I changed the Java folder to be ApplicationJava

**Comment by andersevenrud** [comment] 2017-08-17 20:58
I followed the *exact* steps from your comment, but still cannot reproduce any error.

Do you have unchanged things that you have not commited to git or something ?!

**Comment by andersevenrud** [comment] 2017-08-17 20:58
I see from your latest commit:

```
-        "className": "Java",
 +        "className": "ApplicationJava",
```

This is what fixed it.

**Comment by andersevenrud** [comment] 2017-08-17 20:59
That's why I asked about `className`.

**Comment by SpaceboyRoss01** [comment] 2017-08-17 20:59
I'm rebuild my test installation, but I think it will work.

**Comment by SpaceboyRoss01** [comment] 2017-08-17 21:12
Now there are no errors

**Comment by andersevenrud** [comment] 2017-08-17 21:13
Then my guess is either:

1. Wrong `className` was used
2. Wrong `OSjs.Applications.*` was defined
3. Something was cached
4. You did something I could not reflect from the Github repository you have

Either way, glad to hear it was resolved :)

**Closed by andersevenrud** 2017-08-17 21:13 UTC
Labels: non-issue

**Comment by andersevenrud** [comment] 2017-08-17 21:21
If you experience something like this again, you can actually see all the registered packages in the browser console if you do this: `OSjs.require('core/package-manager').getPackages()` the keys in the object returned is what is looked up when you try to launch an application (The `className`).

It's the `className` that is used to launch an application. It's sort of the "internal name". So this has to be correct in *both* your metadata *and* application main file.

If you experience something similar, feel free to re-open this issue.
