### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Mantraxyz** [os-js/OS.js#661] opened 2018-01-04 21:13 UTC
An error occured while trying to launch: ApplicationSettings

> Application 'ApplicationSettings' preloading failed:  /packages/target/Settings/combined.js?20025

**Comment by andersevenrud** [comment] 2018-01-05 15:10
I'm cloising this issue as it is a duplicate of https://github.com/os-js/OS.js/issues/663#issuecomment-355577349

**Closed by andersevenrud** 2018-01-05 15:10 UTC
