### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by Mantraxyz** [os-js/OS.js#660] opened 2018-01-04 18:35 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationArduinoCiaoConfiguratorWindow.prototype.init/<@http://mdrarduino.local/packages/target/ArduinoCiaoConfigurator/combined.js?44076:69:1
callAPI/<@http://mdrarduino.local/packages/target/ArduinoCiaoConfigurator/combined.js?44076:212:14
doAPICall/<@http://mdrarduino.local/osjs.js:1756:7
onerror@http://mdrarduino.local/osjs.js:9466:9
onReadyStateChange@http://mdrarduino.local/osjs.js:1266:11

```

**Comment by andersevenrud** [comment] 2018-01-05 15:10
I'm cloising this issue as it is a duplicate of https://github.com/os-js/OS.js/issues/663#issuecomment-355577349

**Closed by andersevenrud** 2018-01-05 15:10 UTC
