### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by kkotaro** [os-js/OS.js#281] opened 2016-01-17 23:53 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

**Comment by andersevenrud** [comment] 2016-01-18 10:53
Duplicate of  #185

**Closed by andersevenrud** 2016-01-18 10:53 UTC
