### ISSUE TITLE
[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by pcs3rd** [os-js/OS.js#533] opened 2016-12-03 00:05 UTC
**This bugreport was generated by OS.js 2.0-alpha81:**

> An error occured while trying to launch: ApplicationVNC

> Application 'ApplicationVNC' preloading failed: 
/packages/extras/VNC/vendor/noVNC/include/util.js,/packages/extras/VNC/vendor/noVNC/include/webutil.js,/packages/extras/VNC/vendor/noVNC/include/base64.js,/packages/extras/VNC/vendor/noVNC/include/websock.js,/packages/extras/VNC/vendor/noVNC/include/des.js,/packages/extras/VNC/vendor/noVNC/include/keysymdef.js,/packages/extras/VNC/vendor/noVNC/include/keyboard.js,/packages/extras/VNC/vendor/noVNC/include/input.js,/packages/extras/VNC/vendor/noVNC/include/display.js,/packages/extras/VNC/vendor/noVNC/include/rfb.js,/packages/extras/VNC/vendor/noVNC/include/keysym.js,/packages/extras/VNC/vendor/noVNC/include/inflator.js

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36","platform":"Linux i686","language":"en-US","appVersion":"5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"}
```

**Comment by andersevenrud** [comment] 2016-12-03 11:01
Duplicate of #534

**Closed by andersevenrud** 2016-12-03 11:01 UTC
Labels: duplicate
