### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by shorero** [os-js/OS.js#522] opened 2016-10-31 13:56 UTC
OS: CentOS 7.2

## Expected behaviour
Install with no errors; successful connection to the example app on "localhost"

## Actual behaviour
Following the documented installation steps. After the "grunt" command I see the following output:

```
Running "build:packages" (build) task
Building dist:default/About
Building dist:default/Broadway
Building dist:default/Calculator
Building dist:default/CoreWM
{ Error: ENOENT: no such file or directory, open '/home/shore/LocalGit/OS.js/dist/packages/default/CoreWM/panelitems/windowlist.js'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.fs.readFileSync (fs.js:508:33)
  at /home/shore/LocalGit/OS.js/src/build/packages.js:109:37
  at Array.forEach (native)
  at _combineResources (/home/shore/LocalGit/OS.js/src/build/packages.js:101:18)
  at /home/shore/LocalGit/OS.js/src/build/packages.js:289:17
  at _next (/home/shore/LocalGit/OS.js/src/build/utils.js:137:16)
  at Object.iterate (/home/shore/LocalGit/OS.js/src/build/utils.js:142:7)
  at _buildLess (/home/shore/LocalGit/OS.js/src/build/packages.js:220:12)
  at /home/shore/LocalGit/OS.js/src/build/packages.js:288:15
  at ReadStream.cb (/home/shore/LocalGit/OS.js/node_modules/ncp/lib/ncp.js:217:38)
  at ReadStream.g (events.js:291:16)
  at emitNone (events.js:91:20)
  at ReadStream.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/shore/LocalGit/OS.js/dist/packages/default/CoreWM/panelitems/windowlist.js' } 'Error: ENOENT: no such file or directory, open \'/home/shore/LocalGit/OS.js/dist/packages/default/CoreWM/panelitems/windowlist.js\'\n  at Error (native)\n  at Object.fs.openSync (fs.js:640:18)\n  at Object.fs.readFileSync (fs.js:508:33)\n  at /home/shore/LocalGit/OS.js/src/build/packages.js:109:37\n  at Array.forEach (native)\n  at _combineResources (/home/shore/LocalGit/OS.js/src/build/packages.js:101:18)\n  at /home/shore/LocalGit/OS.js/src/build/packages.js:289:17\n  at _next (/home/shore/LocalGit/OS.js/src/build/utils.js:137:16)\n  at Object.iterate (/home/shore/LocalGit/OS.js/src/build/utils.js:142:7)\n  at _buildLess (/home/shore/LocalGit/OS.js/src/build/packages.js:220:12)\n  at /home/shore/LocalGit/OS.js/src/build/packages.js:288:15\n  at ReadStream.cb (/home/shore/LocalGit/OS.js/node_modules/ncp/lib/ncp.js:217:38)\n  at ReadStream.g (events.js:291:16)\n  at emitNone (events.js:91:20)\n  at ReadStream.emit (events.js:185:7)\n  at endReadableNT (_stream_readable.js:974:12)\n  at _combinedTickCallback (internal/process/next_tick.js:74:11)\n  at process._tickCallback (internal/process/next_tick.js:98:9)\n'
{ Error: ENOENT: no such file or directory, open '/home/shore/LocalGit/OS.js/dist/packages/default/CoreWM/panelitems/weather.js'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.fs.readFileSync (fs.js:508:33)
  at /home/shore/LocalGit/OS.js/src/build/packages.js:109:37
  at Array.forEach (native)
  at _combineResources (/home/shore/LocalGit/OS.js/src/build/packages.js:101:18)
  at /home/shore/LocalGit/OS.js/src/build/packages.js:289:17
  at _next (/home/shore/LocalGit/OS.js/src/build/utils.js:137:16)
  at Object.iterate (/home/shore/LocalGit/OS.js/src/build/utils.js:142:7)
  at _buildLess (/home/shore/LocalGit/OS.js/src/build/packages.js:220:12)
  at /home/shore/LocalGit/OS.js/src/build/packages.js:288:15
  at ReadStream.cb (/home/shore/LocalGit/OS.js/node_modules/ncp/lib/ncp.js:217:38)
  at ReadStream.g (events.js:291:16)
  at emitNone (events.js:91:20)
  at ReadStream.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/shore/LocalGit/OS.js/dist/packages/default/CoreWM/panelitems/weather.js' } 'Error: ENOENT: no such file or directory, open \'/home/shore/LocalGit/OS.js/dist/packages/default/CoreWM/panelitems/weather.js\'\n  at Error (native)\n  at Object.fs.openSync (fs.js:640:18)\n  at Object.fs.readFileSync (fs.js:508:33)\n  at /home/shore/LocalGit/OS.js/src/build/packages.js:109:37\n  at Array.forEach (native)\n  at _combineResources (/home/shore/LocalGit/OS.js/src/build/packages.js:101:18)\n  at /home/shore/LocalGit/OS.js/src/build/packages.js:289:17\n  at _next (/home/shore/LocalGit/OS.js/src/build/utils.js:137:16)\n  at Object.iterate (/home/shore/LocalGit/OS.js/src/build/utils.js:142:7)\n  at _buildLess (/home/shore/LocalGit/OS.js/src/build/packages.js:220:12)\n  at /home/shore/LocalGit/OS.js/src/build/packages.js:288:15\n  at ReadStream.cb (/home/shore/LocalGit/OS.js/node_modules/ncp/lib/ncp.js:217:38)\n  at ReadStream.g (events.js:291:16)\n  at emitNone (events.js:91:20)\n  at ReadStream.emit (events.js:185:7)\n  at endReadableNT (_stream_readable.js:974:12)\n  at _combinedTickCallback (internal/process/next_tick.js:74:11)\n  at process._tickCallback (internal/process/next_tick.js:98:9)\n'
Building dist:default/Draw
Building dist:default/FileManager
Building dist:default/HTMLViewer
Building dist:default/MusicPlayer
Building dist:default/Preview
Building dist:default/ProcessViewer
Building dist:default/Settings
Building dist:default/Textpad
Building dist:default/Writer
Building dist-dev:default/About
Building dist-dev:default/Broadway
Building dist-dev:default/Calculator
Building dist-dev:default/CoreWM
Building dist-dev:default/Draw
Building dist-dev:default/FileManager
Building dist-dev:default/HTMLViewer
Building dist-dev:default/MusicPlayer
Building dist-dev:default/Preview
Building dist-dev:default/ProcessViewer
Building dist-dev:default/Settings
Building dist-dev:default/Textpad
Building dist-dev:default/Writer

Running "generate:apache-htaccess" (generate) task
Generating apache-htaccess
undefined
```

Checking the directory mentioned in the stack trace, I find that dist/packages/default/CoreWM/panelItems does in fact contain weather.js and windowlist.js. When I run bin/start-dist.sh to start the server, I see no errors. However, any attempt to connect to localhost:8000 produces an error dialog -- something about a type error and a particular URL not being a constructor (passes too fast for me to capture). At this point the app seems damaged beyond repair; for example, hitting the "settings" button on the menu bar fills the screen with an infinite number of overlapping windows.

## Steps to reproduce the error
Follow the documented installation steps. The same thing happened during two independent installs.

## (Optinal) Browser and OS information
Browser: Firefox 45.4.0 (most recent version from the Centos 7.2 repositories).
OS: Centos OS 7.2 (updated today)
Uname: Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andersevenrud** [comment] 2016-10-31 15:05
Strange. I can't reproduce this error on my machine(s). Did a fresh clone and then:

```
npm install --production
grunt
./bin/start-dist.sh
```

Even stranger, is that it reports of missing files when you have in fact found them to be where they should -- also that no other packages are failing... they all build the same.

If CoreWM fails, then pretty much everything becomes messed up with the UI.

Do you have any problems running the developer environment (which does not need this build process) ?
`./bin/start-dev.sh`

**Comment by shorero** [comment] 2016-10-31 16:13
Will get back to you -- am building another VM with Ubuntu to try it.

**Comment by shorero** [comment] 2016-11-01 11:16
OK. I started this AM with a clean VM and did a reinstall, following the
instructions. I note the following oddities:

1. During the "grunt" run there's a complaint about a missing module
"mocha". I subsequently reset the VM and did "npm install mocha" prior to
the --production install. This got rid of that complaint.

2. During the --production install I note that there's a warning about
"prefer to use global version of coffee-script" or words to that effect. I
tried several approaches to removing this warning (resetting the VM prior
to each), including
  a. npm install -g coffee-script
  b. npm install -g coffee-script@1.10.0 (this is the version pulled in
during the --production install)
  c. npm install -g grunt (the grunt stuff has a dependency on
coffee-script)
  d, npm install -g grunt@1.0.1 (this is the version that --production
actually pulls in)
I couldn't get rid of the warning, no matter what I did, so I conclude that
it's not a big problem.

Anyway, after all my experimenting, I reset and did the installation steps,
adding only the mocha install. I got the same build errors during the grunt
command. Command bin/start-dist.sh still produced the error when I hit
:8000 with the browser; I noted this time that the error is coming from the
CoreWM module, which makes sense since that's where the grunt errors are.

However, as you may have suspected, I have no problems when I run
bin/start-dev.sh -- no errors when I connect, and the settings window comes
up without barfing new windows across the browser.

Oh, I also should mention that OS.js is reporting version 2.0.0-alpha80

**Comment by shorero** [comment] 2016-11-01 11:17
Also should mention that this is still Centos 7.2 -- haven't tried Ubuntu
yet, and may not, given that the devel server works under Centos (unless
you'd like me to try Ubuntu)

**Comment by andersevenrud** [comment] 2016-11-01 11:33
> 1. During the "grunt" run there's a complaint about a missing module
"mocha". I subsequently reset the VM and did "npm install mocha" prior to
the --production install. This got rid of that complaint.

This is just a warning, really.

> 2. During the --production install I note that there's a warning about
"prefer to use global version of coffee-script" or words to that effect.

This is also just a warning. And comes from a dependency package.

> However, as you may have suspected, I have no problems when I run
bin/start-dev.sh -- no errors when I connect, and the settings window comes
up without barfing new windows across the browser.

Yep. This is because the developer build loads the code directly from source. So it does not matter if the package build failed or not.

> Also should mention that this is still Centos 7.2

I have tested this on a Debian and Arch box without any problems, so I'm suspecting something with Centos or your setup. By all means, give it a go. Then we can narrow it down easier.

**Comment by andersevenrud** [comment] 2016-11-03 11:12
You don't by any chance get any security errors in your logs on CentOS? 

I am noticing that a lot of people have downloaded and installed OS.js in the recent month, without any reports of similar problems -- so my suspect is CentOS or some of the packages it uses that OS.js is dependent upon. Still though, so weird that you get a ENOENT  in that spesific spot in the build process

**Comment by shorero** [comment] 2016-11-04 09:35
Sorry, but I didn't check the security logs, and I've slicked the VM since
then. However, the default Centos security profile is pretty permissive --
not to mention the fact that the issue seems to be confined to the
"production" stuff. I agree that there's probably something Centos-specific
that's the issue, but I can't tell what it is any more.

**Comment by vincent-pli** [comment] 2016-11-28 09:18
Hi, I get the same error on my mac, any suggestion for it?

**Comment by andersevenrud** [comment] 2016-11-28 09:19
@vincent-pli Can you try the `developer` branch ?

**Comment by andersevenrud** [comment] 2016-11-28 14:46
@vincent-pli Did it work out for you ?

**Comment by andersevenrud** [comment] 2016-11-28 21:08
@shorero Well... I got around to installing CentOS just to try out and I did not encounter this problem. So now I'm sitting here scratching my head and wondering how the hell this is a problem Oo

Could you do me a favor and test the `development` branch ? Grunt is no longer used here, so you'll have to run `node osjs build` instead (then `node osjs run` to try out). Make sure to run `npm install --production` if you switch branches from an already cloned repo.

**Comment by shorero** [comment] 2016-11-30 13:55
Yes, using the development branch I was able to get the desktop up. I've
been sucked off onto other stuff and haven't gotten back to OS.js since,
though.

**Comment by andersevenrud** [comment] 2016-11-30 13:57
@shorero Thanks for checking it out for me. Much appreciated! :)

Then I know at least there was something wrong in the previous iteration of the build system and that it has been fixed.

I'm going to merge all the changes into `master` today, so I can finally resolve this issue :)

**Comment by andersevenrud** [comment] 2016-11-30 18:00
I've merged everything into master now. So this should be resolved! :)

Let me know if it's not!

**Comment by andersevenrud** [comment] 2016-11-30 18:00
Release docs: http://community.os.js.org/t/update-version-bump-alpha81/105

**Closed by andersevenrud** 2016-11-30 18:00 UTC
Labels: open for suggestions, possible bug
