### ISSUE TITLE
HTTP Error 502 from /vfs/writefile request

### ISSUE THREAD

**Issue by valp124** [os-js/OS.js#774] opened 2021-06-11 21:08 UTC
When uploading a file from File Manager, an error occurs if the file is large enough for the upload to last a substantial amount of time. _Substantial_ seems to vary, unfortunately. I have observed it in as little as 75 sec, but most of the time it's on the order of ~4 min. The error looks like this:

![image](https://user-images.githubusercontent.com/7969539/121746894-94027a80-cad4-11eb-81d8-a11c176d1c1f.png)

Over a slow connection, as little as 40Mb will cause it; on a fast link, it takes gigabytes. It fails even when browsing from _within_ the same server (not as `localhost`, to the FQDN), only there it takes ~30Gb to fail it.

This started happening just recently and only on one new server we have just built. The code is exactly the same though as on the server we migrated from. We are on version `3.1.11` of `osjs/server`. I know it's not the latest, but the same version worked fine earlier... `filemanager-application` is on the latest (`1.5.2` as of today).

The stack I get is:

&nbsp; | te | @ | fetch.js:103
-- | -- | -- | --
&nbsp; | value | @ | core.js:488
&nbsp; | (anonymous) | @ | system.js:34
&nbsp; | writefile | @ | system.js:73
&nbsp; | (anonymous) | @ | vfs.js:114
&nbsp; | value | @ | filesystem.js:335
&nbsp; | value | @ | filesystem.js:296
&nbsp; | (anonymous) | @ | filesystem.js:153
&nbsp; | m | @ | index.js:286
&nbsp; | e | @ | index.js:343
&nbsp; | t.onchange | @ | index.js:105

Note that _download_ works just fine, no matter how long it takes. Only upload fails.

Have been at it for two full days already, still scratching my head...

**Comment by andersevenrud** [comment] 2021-06-11 21:45
Since this is a 502 I'm guessing that you're running a reverse-proxy here. 

>  It fails even when browsing from within the same server

Have you tried to do this directly onto the node server instead of the reverse-proxy ?

**Comment by valp124** [comment] 2021-06-11 21:47
> Since this is a 502 I'm guessing that you're running a reverse-proxy here.
> 
> > It fails even when browsing from within the same server
> 
> Have you tried to do this directly onto the node server instead of the reverse-proxy ?

Yes, but not on the same system. It doesn't fail.

**Comment by andersevenrud** [comment] 2021-06-11 21:54
Thanks for the additional information here. I'll have a look this weekend.

**Comment by valp124** [comment] 2021-06-11 21:57
> Thanks for the additional information here. I'll have a look this weekend.

I have a strong feeling that I'll end up being embarrassed when we finally get to the bottom of it... At this point though, I can't think of _anything_ that we're doing differently on this system. We switched to node 14, true, but we also tested with 11 that was used earlier, to the same effect.

**Comment by andersevenrud** [comment] 2021-06-11 22:04
Working with HTTP applications can be a pain in the butt to debug in cases like this, so I feel for 'ya.

Seeing that this is a 502 a thing that immediately comes to mind is that timeout is incorrectly configured in the proxy or just too low.

**Comment by valp124** [comment] 2021-06-11 22:05
> Working with HTTP applications can be a pain in the butt to debug in cases like this, so I feel for 'ya.
> 
> Seeing that this is a 502 a thing that immediately comes to mind is that timeout is incorrectly configured in the proxy or just too low.

Thing is, I literally copied all of the apache files (I use it from xampp), so everything is identical to what it was before...

**Comment by valp124** [comment] 2021-06-11 22:10
Literally everything, every binary file, every config. Everything is in one `/xampp` folder.
Moreover, I'm reverse-proxying another app through it (it's a PHP app), and uploads there work just fine...

**Comment by andersevenrud** [comment] 2021-06-11 22:20
Ah. I just tried some tests on my end and I was able to upload a 20 gig file no problem, even behind nginx. I also tested the file max upload size limited just to be sure that did not cause any disruption that could lead to a 502, and thankfully no.

I'll do a bit more testing on different envs/oses and Apache this weekend. I just recently set up a Windows machine here for testing, which finally gets some use :)

**Comment by valp124** [comment] 2021-06-12 00:27
> Ah. I just tried some tests on my end and I was able to upload a 20 gig file no problem, even behind nginx. I also tested the file max upload size limited just to be sure that did not cause any disruption that could lead to a 502, and thankfully no.
> 

Just remember that it's not the file size _per se_, but rather the time that seems to be the issue...

> I'll do a bit more testing on different envs/oses and Apache this weekend. I just recently set up a Windows machine here for testing, which finally gets some use :)

You're the best of the best!!

**Comment by andersevenrud** [comment] 2021-06-12 01:14
> Just remember that it's not the file size per se, but rather the time that seems to be the issue...

Yup. I ran this on a simulated connection right after the issue was opened so it ran for a really long time. However, I ran this on my development setup which has a ton of other variables in it overall when it comes to testing.

I'll get back to 'ya :)

**Comment by valp124** [comment] 2021-06-12 03:00
Oh, I haven't mentioned: all this reverse-proxying is because Apache lets me server it over https. I can't imagine that SSL would make this happen, but then again, I can't imagine what would.

**Comment by valp124** [comment] 2021-06-15 04:43
Another quick update: I found this and tried it -- didn't help.

https://serverfault.com/questions/185894/proxy-error-502-reason-error-reading-from-remote-server-with-apache-2-2-3-de

**Comment by andersevenrud** [comment] 2021-06-15 18:15
I sadly didn't get as much time this weekend to look into this as I wanted. So I still haven't been able to reproduce this. I will set a reminder for this though and resume ASAP.

**Comment by valp124** [comment] 2021-06-15 21:10
Man, I feel so bad even asking you to look into it. I have a gut feeling that it'll end up being a problem 100% on my side. I have by now looked _everywhere_ I could and still can't spot what has changed in this new server. 

But while I was doing all this looking, a thought occurred to me that I was just chatting about a moment ago with @josephjeno: would it be possible to do file upload through the web socket instead of HTTP?

**Comment by andersevenrud** [comment] 2021-06-15 21:59
> would it be possible to do file upload through the web socket instead of HTTP

It would be possible, but I'm not really sure if there's any advantage to it.

**Comment by valp124** [comment] 2021-06-16 14:54
I'm _far_ from an expert on the subject... I suppose, in this particular case, it would solve the issue because ws connection is persistent (I assume that someone drops HTTP connection during the file transfer, leading to 502). But also, it seems like there are some advantages of ws for file transfers that people discuss out there...

https://www.accelebrate.com/blog/file-uploads-web-sockets-part-3-of-3
https://stackoverflow.com/questions/14703627/websockets-protocol-vs-http

Pardon my naive reading of that...

**Comment by valp124** [comment] 2021-06-16 14:55
And https://blog.feathersjs.com/http-vs-websockets-a-performance-comparison-da2533f13a77

**Comment by andersevenrud** [comment] 2021-06-16 15:10
I was reading up on this myself when you mentioned it and I'm not sold yet on this :D I'll have to try this for myself.

**Comment by valp124** [comment] 2021-06-16 20:41
I know, I'm not sold either. Just quoting what others are saying 😜

**Comment by valp124** [comment] 2021-06-17 16:05
You know... I have just spotted an exception in the server log that is printed when the upload fails like that. I'd like to say that it happens _every_ time, but the truth is that in some instances it doesn't. As soon as I reload the page though, it starts happening and keeps happening (on the failed uploads, that is) until something gets stale. Anyway, here's the error:

```
WARN  Request aborted

  at IncomingMessage.<anonymous> (node_modules\formidable\lib\incoming_form.js:122:19)
  at IncomingMessage.emit (events.js:315:20)
  at IncomingMessage.EventEmitter.emit (domain.js:485:12)
  at abortIncoming (_http_server.js:541:9)
  at socketOnClose (_http_server.js:533:3)
  at Socket.emit (events.js:327:22)
  at Socket.EventEmitter.emit (domain.js:485:12)
  at TCP.<anonymous> (net.js:670:12)
```

**Comment by andersevenrud** [comment] 2021-06-17 16:26
Hm. Was that the whole exception ?  Looks a bit short.

**Comment by andersevenrud** [comment] 2021-06-17 18:15
Just out of interest.... If you edit `node_modules/@osjs/server/src/core.js` and add the following does that take care of it ? I'm just trying to attack this from the bottom up. If this does not solve it I'll have to look into the formidable package.

```js
this.httpServer.setTimeout(60 * 1000) // minutes
```

above:

https://github.com/os-js/osjs-server/blob/b1a6c888843d7de9eb1b4011a3242c4ea056364b/src/core.js#L219

**Comment by valp124** [comment] 2021-06-17 18:51
Yep, that was the whole exception. I'll do that test, but I'll have to wait for a quiet moment sometime in the middle of the night when no one is working, because it only happens on the production server... 😳

**Comment by andersevenrud** [comment] 2021-06-17 19:08
> because it only happens on the production server

Uh, oh! :D

**Comment by valp124** [comment] 2021-07-19 15:54
Ok, finally had a chance to test out your suggestion. It hasn't helped (predictably)... The day I understand what's happening there, I'll go and get drunk.

**Comment by andersevenrud** [comment] 2021-07-19 16:25
One thing I've forgotten to ask about here is the HTTP request headers. Could you maybe take a screenshot or something of that when it fails ?

Also, is this reproducible on other machines ? Is it reproducible in a completely fresh VM ?

Still haven't been able to reproduce this myself :(

**Comment by andersevenrud** [comment] 2021-07-19 16:27
And, hey, if we get to the bottom of this, that round is on me.

**Comment by valp124** [comment] 2021-07-19 16:33
It's not reproducible on a dev machine. I'd have to set up another system just like this production one, with Apache and a whole nine yards, to know if I can reproduce it there, and I don't have an easy option for that (not _im_possible though...). Mind you: this didn't use to happen on a seemingly identical machine and a seemingly identical build before I migrated to this new server...

**Comment by andersevenrud** [comment] 2021-07-19 17:21
> It's not reproducible on a dev machine

I was thinking on the client side of things. To eliminate some variables just run a completely fresh OS and browser without extensions, etc.

**Comment by andersevenrud** [comment] 2021-07-19 17:36
Btw, there's a way to reproduce the same error message, but in another scenario. If you simulate a really slow network speed, then upload a file, and close the tab:

```
 WARN  Request aborted                                                                                                                                                                                                       internal 19:33:04

  at IncomingMessage.<anonymous> (/home/anders/Projects/OS.js/packages/osjs-server/node_modules/formidable/lib/incoming_form.js:122:19)
  at IncomingMessage.emit (events.js:314:20)
  at abortIncoming (_http_server.js:550:9)
  at socketOnClose (_http_server.js:543:3)
  at Socket.emit (events.js:326:22)
  at TCP.<anonymous> (net.js:672:12)
```

Just out of curiousity, do you see this above this exception ?

```
POST /vfs/writefile - - - - ms
```

Or this ?

```
WebSocket connection closed
```

**Comment by andersevenrud** [comment] 2021-07-19 18:25
Speaking of logs... this 502 error is really confusing to me. This normally means that the OS.js server dropped out (though in some rare cases I've seen this being from other network problems). How is the server running ? Some process manager that restarts the server on demand ?

**Comment by valp124** [comment] 2021-07-19 19:26
> > It's not reproducible on a dev machine
> 
> I was thinking on the client side of things. To eliminate some variables just run a completely fresh OS and browser without extensions, etc.

This was reported by multiple people, so the sample of client environments is probably large enough to assume that there isn't a single culprit...

**Comment by valp124** [comment] 2021-07-19 19:29
> Btw, there's a way to reproduce the same error message, but in another scenario. If you simulate a really slow network speed, then upload a small file (... or just upload a large file, lol), and close the tab:
> 

Yes, I see these every time upload fails.
```
 WARN  Request aborted

  at IncomingMessage.<anonymous> (node_modules\formidable\lib\incoming_form.js:122:19)
  at IncomingMessage.emit (events.js:315:20)
  at IncomingMessage.EventEmitter.emit (domain.js:485:12)
  at abortIncoming (_http_server.js:541:9)
  at socketOnClose (_http_server.js:533:3)
  at Socket.emit (events.js:327:22)
  at Socket.EventEmitter.emit (domain.js:485:12)
  at TCP.<anonymous> (net.js:670:12)
```

**Comment by valp124** [comment] 2021-07-19 19:37
> Speaking of logs... this 502 error is really confusing to me. This normally means that the OS.js server dropped out (though in some rare cases I've seen this being from other network problems or running out of memory/available connections). How is the server running ? Some process manager that restarts the server on demand ?

This is an interesting idea, about running out of memory... Well, no. The size of the file that causes failure hugely depends on the bandwidth. It would have to be in tens of Gb to fail when the client is local, but only a few Mb when remote.

The server is running all the time. I run it as a service (created with NSSM -- because creating a service in Windows is a task for the brave 😲)

**Comment by andersevenrud** [comment] 2021-07-19 19:40
> Yes, I see these every time upload fails.

Yup, but in my case it was a user action, which we can pretty much rule out from your side. In any scenario when a connection drops that's the error one will see (basically a `Connection reset by peer`.)

> run it as a service (created with NSSM

I see. So at least it's some kind of resurrection mechanic there. Now, I'm interested if there's any crash reports in there. Because that will explain the 502 issue.

Ideally the OS.js server log should have some kind of indication that there was a crash though, which would happen after the `Request aborted` message(s).

**Comment by valp124** [comment] 2021-07-19 20:57
Nope, except for that exception, the server is happy as a clam and continues plugging along.

**Comment by andersevenrud** [comment] 2021-07-19 21:34
And no other system logs to indicate any network issues ? :man_shrugging:

**Comment by valp124** [comment] 2021-07-20 14:18
Sorry, didn't notice your last question. Nothing that I can spot in any obvious place...

**Comment by andersevenrud** [comment] 2021-07-20 14:22
Apache logs are also clean ?

**Comment by valp124** [comment] 2021-07-20 15:17
Except for those proxy errors I pasted earlier...

**Comment by andersevenrud** [comment] 2021-07-20 15:56
Not sure how I missed that :man_facepalming: 

But at least now we can eliminate the OS.js server and the browser as the fault here. I'm fairly confident in that.

Kind of infuriating that I can't reproduce this myself. I even ran an upload running all night using Apache as a reverse proxy on a fresh instance without issues.

I wonder, If you set `SetEnv proxy-sendchunked` in your apache config, does that do anything ? Apache by default buffers the request before handing it off to the server. If theres some kind of timeout while buffering, then I could see how this fails. This enables a chunked mechanic instead. As to why though, I would not have a clue :D

**Comment by valp124** [comment] 2021-07-20 20:58
Nope. That didn't help, either. What's infuriating is that this used to work on a seemingly identical server. (There are some differences in the BIOS configuration, having to do with CPU tuning, but that can't possibly affect this issue.)

**Comment by andersevenrud** [comment] 2021-07-20 21:02
And this server is on the same network as well I assume ? If it's a physical machine, then I suppose hardware configuration can have something to do with it... but there should have been some kind of trace of anything in that manner in the system logs.

If the storage is over network, then I'd look into that. Right now, I'm kind of running out of things to try :sweat_smile:

**Comment by valp124** [comment] 2021-07-20 21:12
Yep... It's a physical machine, on the same network as before, even in the same switch. There's absolutely nothing to write home about in the event log... The storage is a local drive. I even tried mapping nfs to a different drive, just to eliminate that variable. I'm completely out of ideas at this point. What saves me is that I have a dedicated up/download client-server (client is CLI and server is mapped to write to the same vfs location) for those who run into this problem. The CLI feeds back the upload progress, so folks kind of like it 🙂

**Comment by andersevenrud** [comment] 2021-07-20 21:34
At least you have some kind of workaround in place :sweat_smile: 

Now that you've mentioned CLI, one thing that would be interesting is to test a tool like curl to eliminate both the browser and the OS.js client. It's possible to copy the cookie with devtools in the browser to use it to perform requests.

Ex:

```shell
curl -X POST \
  --limit-rate 128K \
  --cookie 'osjs.sid=the-session-id-here' \
  --form upload='@filename-from-current-directory' \
  --form path='home:/destination-filename' \
  http://localhost:8000/vfs/writefile
```

**Comment by andersevenrud** [comment] 2021-07-20 21:38
I know I said that we could rule those out...but it might be an easier way to reproduce, and maybe there's some additional info that comes up.

**Comment by valp124** [comment] 2021-07-20 21:55
Hmm... I get an error, and I'm stumped about its origin...

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   334  100    76  100   258   1013   3440 --:--:-- --:--:-- --:--:--  4513{"error":"TypeError: Cannot read property 'path' of undefined","stack":null}
```

**Comment by andersevenrud** [comment] 2021-07-20 22:06
If you're on windows then there might be some command argument syntax that differs :man_shrugging:

**Comment by valp124** [comment] 2021-07-20 22:12
Ok. I simply forgot `@` in front of the file name. Man, you're good! I had no idea about this curl syntax 🤓

On to trying a large file...

**Comment by valp124** [comment] 2021-07-20 22:29
Talk about bizarre, dude... Curl is happily counting off bytes transferred. In the meantime, there was an error in the Apache after about a minute since I hit enter, and the accompanying exception in the osjs server log (it's not timestamped, but I'm sure it happened at the same time). My guess is that curl will spit out the error after it thinks the entire file is transferred. That's going to take another couple of hours though. I'll try on a smaller file a bit later.

**Comment by andersevenrud** [comment] 2021-07-20 22:32
Now that's Interesting! Throw on a `-v` to get more information out of curl, and `--fail-early` might make it bail.

**Comment by andersevenrud** [comment] 2021-07-20 22:33
A bit lazy  to look up in the thread...but you have tried just using the OS.js server directly on port 8000 and not directly via Apache, right ?

**Comment by andersevenrud** [comment] 2021-07-20 22:49
> My guess is that curl will spit out the error after it thinks the entire file is transferred

I had to think about this for a while... if curl just keeps chugging along after you see errors that would mean that the connection between nodejs and Apache went down, and Apache did not terminate the client (curl) request -- which would be suuuper wacky, especially considering you saw a 502 in the browser :thinking:

**Comment by valp124** [comment] 2021-07-21 02:14
4.5 hours later, it's still chugging along, and I'm too lazy to interrupt it and try on a smaller file. I'm just curious about what's going to happen. (The file was only 2Gb, by the way, and this is presumably on the LAN...  It looks like 128kbps is all it can muster.) I'll tell you in the morning what happened. Suuuper wacky is exactly right.

**Comment by valp124** [comment] 2021-07-21 12:46
Well, ok, it's stupid what curl does, but at least it's not insane. At the end of all those hours, it did print out error 502.

**Comment by andersevenrud** [comment] 2021-07-21 12:56
The browser must surely exhibit the same behavior here... curl is just a HTTP client after all :sweat_smile:

**Comment by valp124** [comment] 2021-07-21 12:56
Alright, here's something more interesting, and it rehabilitates Apache. So what I did yesterday was `curl` to the proxy URL. Just now I tried the same file, but this time directly to the osjs server. (Without your curl tip I had no way of trying this from the browser!). So here's what I get:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 2048M    0     0    0 7808k      0   128k  4:33:02  0:01:00  4:32:02  128k
curl: (56) Recv failure: Connection was reset
```

Note: a) it happens exactly after 1 min; b) this time curl quits right away; and of course, c) Apache isn't in the game at all.
And yes, there is an exception in the osjs server log, as always:

```
 WARN  Request aborted

  at IncomingMessage.<anonymous> (node_modules\formidable\lib\incoming_form.js:122:19)
  at IncomingMessage.emit (events.js:315:20)
  at IncomingMessage.EventEmitter.emit (domain.js:485:12)
  at abortIncoming (_http_server.js:541:9)
  at socketOnClose (_http_server.js:533:3)
  at Socket.emit (events.js:327:22)
  at Socket.EventEmitter.emit (domain.js:485:12)
  at TCP.<anonymous> (net.js:670:12)
```

**Comment by valp124** [comment] 2021-07-21 12:58
> The browser must surely exhibit the same behavior here... curl is just a HTTP client after all 😅

Well, you'd think so, but in the browser you get the error right away, whereas curl waited ALL the way till the end. But anyway, that's not important.

**Comment by andersevenrud** [comment] 2021-07-21 13:10
> a) it happens exactly after 1 min

This is a pretty huge discovery here. 60 seconds is pretty much standard when it comes to timeouts in HTTP.

In nodejs `13.0.0` and above, there is no timeout on the http server by default. On older it seems to be 120 seconds. 

You've already tried messing `server.setTimeout(msecs)` with no effect it seems...hm. Which node version are you on right now ?

> b) this time curl quits right away; 

This should be propagated to Apache, which I talked about earlier. So strange :D

**Comment by valp124** [comment] 2021-07-21 13:19
I'm on node `14.4.0`. Note that this hasn't happened on any builds except on that one server...

**Comment by andersevenrud** [comment] 2021-07-21 13:20
Have you tried punching the computer ?

**Comment by valp124** [comment] 2021-07-21 13:22
😜 I've been working exclusively from home, and my IT guy is on vacation. I'll ask him to do that first thing when he gets back. 😈

**Comment by andersevenrud** [comment] 2021-07-21 13:29
Tell him to give it a good swing from me as well :joy: 

The only value I can find in the nodejs http server that is 60 seconds is the following: https://nodejs.org/api/http.html#http_server_headerstimeout

Not sure what could potentially cause HTTP headers to take more than that I have no idea, but that's all I have now. It can be added like the previous timeout thingy, then restart the node server.

**Comment by andersevenrud** [comment] 2021-07-21 13:49
Also, try updating to `14.17.3` .

**Comment by valp124** [comment] 2021-07-21 15:44
Man oh man oh man oh man! You did it again! That's what it was -- I'll be damned if I know _why_ but `server.headersTimeout` it was!

**Comment by valp124** [comment] 2021-07-21 15:56
Why in the white world this server but not any others I tried?? At any rate, at least part of the mystery is solved!

**Comment by andersevenrud** [comment] 2021-07-21 16:20
Holy tamales! I'd love to know what the frig is going on here :joy: 

Are you running `14.4.0` on those other servers as well ? If not, then it might just be as simple as a b0rked version.

**Comment by andersevenrud** [comment] 2021-07-21 16:36
I think you might just have a bad version... I looked through v14 changelogs, and this was a patch in a later release https://github.com/nodejs/node/commit/7322e58d11

**Comment by valp124** [comment] 2021-07-21 17:36
Well, I thought we were using the same version, but I see now that on at least one build I have `14.8.0`, and (very unfortunately), Joe isn't on the project anymore, so I'm not sure what he was using.

I'll try to upgrade the version. It's always a bit of a nail-biter doing it on the production server...

**Comment by andersevenrud** [comment] 2021-07-21 17:41
As long as you stick with the latest v14 you'll have no issues :crossed_fingers:

**Comment by valp124** [comment] 2021-07-21 20:43
Guess what. Same problem with  14.17.3!

**Comment by andersevenrud** [comment] 2021-07-21 22:31
What the... -- indeed! What did you set the timeout to btw ?

**Comment by valp124** [comment] 2021-07-22 13:23
Set the timeout to 24 hours, just for grins.

Now, I will say that I'm not on the latest `@osjs/server` -- I'm on `3.1.5`, and I see that the latest is `3.2.2`. I suppose I should upgrade... Although I can't imagine that it'll make a difference.

**Comment by andersevenrud** [comment] 2021-07-22 13:26
I've been reading up on this btw.... still none the wiser :joy:

Suppose it doesn't hurt to upgrade at least :)

**Comment by valp124** [comment] 2021-07-22 13:56
Ok, upgraded. I think you know what the answer is...

**Comment by andersevenrud** [comment] 2021-07-22 14:04
Don't tell me it's working now ? :D

**Comment by andersevenrud** [comment] 2021-07-22 14:41
Good.... that would have been too much irony for me to handle :laughing:

**Comment by valp124** [comment] 2021-07-22 14:47
_Some_ network setting on that server affects the headers timeout. Something like this could do it, except that I don't have an NPS...

https://docs.microsoft.com/en-us/answers/questions/47088/idle-timeout-session-timeout-in-constraints-nap-wi.html

**Comment by valp124** [comment] 2021-07-22 14:56
So I guess the next question is, would you be willing to add that line to your server code 😛. (To be sure: it's pretty much a moot point for me now, because to upload a realistically large file, one would have to use that special CLI, anyway, lest they want to wait for hours without feedback and risking a network interruption (as often happens over VPN).)

**Comment by andersevenrud** [comment] 2021-07-22 15:11
> would you be willing to add that line to your server code

I don't feel comfortable adding things that changes nodejs core behavior. You'll have to put this into your own codebase.

> one would have to use that special CLI, anyway

I'll probably have the progress stuff implemented this weekend. I started on it, but got a bit distracted by something else which I now just completed.

**Comment by valp124** [comment] 2021-07-22 15:22
> I don't feel comfortable adding things that changes nodejs core behavior. You'll have to put this into your own codebase.
> 
Sure thing, that's perfectly reasonable.


> I'll probably have the progress stuff implemented this weekend. I started on it, but got a bit distracted by something else which I now just completed.

You're the best!!

**Comment by valp124** [comment] 2021-07-22 20:22
Well, my good man. Are you ready to hear the answer to our woes and meet the murderer?

**Comment by andersevenrud** [comment] 2021-07-22 20:25
It's gonna be something ridiculously obvious isn't it ? :rofl:

**Comment by valp124** [comment] 2021-07-22 20:30
Nope, it won't be. But it'll teach me (for the millionth time) to be sure to eliminate all the complexity when working on a problem like this and test with the bare bones. So my server runs in a service, as I had mentioned, and the service runs `forever` script (https://www.npmjs.com/package/forever) that's supposed to restart the server if it dies for some reason. Well, it's `forever` that's causing the problem. I'm looking at their code to try to figure out why, but no doubt, that's what it is. If I run it from the plain command line, it works just fine!

**Comment by andersevenrud** [comment] 2021-07-22 20:32
Aha! I would not trust `forever`, especially in production. Go for PM2 or something like that instead :D

**Comment by valp124** [comment] 2021-07-22 21:00
Ok, fine, switched to `pm2`. Guess what. Same problem!

**Comment by andersevenrud** [comment] 2021-07-22 21:08
I'll be damned! This is all very bizzare... I know that PM2 hooks into the http stuff so you can perform load balancing etc, but I thought that `forever` was just a simple process spawning daemon. I would sort of understand why this would occur in PM2 since it behaves as mentioned...but with forever. W A T ?!

**Comment by valp124** [comment] 2021-07-22 21:13
Wait. Whaaat?? I have restarted it, this time from `msys2` shell and with more command args (but that's just to add log files paths), and now it's working. Whaaat?? I didn't imagine it, I still have the 502 error on the screen from before. Man, this is insane. Well, the good news (I guess) is that it's working now 🤔

**Comment by andersevenrud** [comment] 2021-07-22 21:15
So...what happens if you switch back to forever for fun ? :thinking:

**Comment by valp124** [comment] 2021-07-22 21:19
Oh, there is no doubt that it'll fail, that I have tried a million times. Well, another good news is that I don't need a service anymore, as `pm2` works in a deamon mode. I think I will consider this case closed 😄
Man, this simply would not have been possible without all your help!

**Comment by andersevenrud** [comment] 2021-07-22 21:29
I'm pretty relieved that it's fixed...but also very curious as to why the heck it happens behind forever.

Guess we can close this one then. Glad to be of help!

**Closed by andersevenrud** 2021-07-22 21:29 UTC
Labels: investegate

**Comment by valp124** [comment] 2021-07-22 21:38
I suppose I should submit an issue to `forever`... They probably don't care that much though. I bet it's the version difference (between the one I had on the old server and the one that was installed on the new one) that broke it.
Thank you so much again!

**Comment by andersevenrud** [comment] 2021-07-22 21:39
Any time!
