### ISSUE TITLE
The calendar was just installed!

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/OS.js#415] opened 2016-06-05 02:54 UTC
An error occured while trying to launch: ApplicationCalendar

> Application 'ApplicationCalendar' preloading failed:  /packages/submissions/Calendar/combined.js

**Comment by andersevenrud** [comment] 2016-06-05 12:32
Duplicate of #417

**Closed** 2016-06-05 12:33 UTC
Labels: duplicate

**Comment by SpaceboyRoss01** [comment] 2016-06-05 18:08
This only happens on Firefox.

**Comment by andersevenrud** [comment] 2016-06-05 18:09
Unable to reproduce :/

Maybe you have some plugins/extensions that prevents the files from loading properly
