### ISSUE TITLE
PID Report Bug or Error

### ISSUE THREAD

**Issue by Mantraxyz** [os-js/OS.js#662] opened 2018-01-05 03:40 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'PID' of null
    at http://mdrarduino.local/packages/target/ArduinoProcessViewer/combined.js?31419:83:24
    at Array.forEach (<anonymous>)
    at http://mdrarduino.local/packages/target/ArduinoProcessViewer/combined.js?31419:81:26
    at http://mdrarduino.local/packages/target/ArduinoProcessViewer/combined.js?31419:64:16
    at ArduinoHandler.<anonymous> (http://mdrarduino.local/osjs.js:1754:7)
    at Object.onsuccess (http://mdrarduino.local/osjs.js:9463:19)
    at XMLHttpRequest.onReadyStateChange (http://mdrarduino.local/osjs.js:1263:16)
```

**Comment by andersevenrud** [comment] 2018-01-05 15:10
I'm cloising this issue as it is a duplicate of https://github.com/os-js/OS.js/issues/663#issuecomment-355577349

**Closed by andersevenrud** 2018-01-05 15:10 UTC
