### ISSUE TITLE
Failed Static IP setup on ETH1

### ISSUE THREAD

**Issue by nairn62** [os-js/OS.js#546] opened 2017-01-13 13:04 UTC
An error occured while trying to launch: ApplicationArduinoLuci

> Application 'ApplicationArduinoLuci' preloading failed:  /packages/target/ArduinoLuci/combined.js?78076

**Comment by andersevenrud** [comment] 2017-01-13 13:05
Duplicate of #542

> Aha, I see. Yes, there seems to be an issue with the webserver on that board -- which is being investegated.

**Closed by andersevenrud** 2017-01-13 13:05 UTC

**Comment by andersevenrud** [comment] 2017-01-13 13:07
Btw, You can still use Luci (which is also installed on the board) to configure stuff.
