### ISSUE TITLE
tian error

### ISSUE THREAD

**Issue by graffiti4u** [os-js/OS.js#439] opened 2016-07-08 15:22 UTC
An error occured while trying to launch: ApplicationArduinoWizardSettings

> Application 'ApplicationArduinoWizardSettings' preloading failed:  /packages/target/ArduinoWizardSettings/combined.js?13636

**Comment by andersevenrud** [comment] 2016-07-08 15:23
Duplicate of #437, ref: #436

**Closed by andersevenrud** 2016-07-08 15:23 UTC
