### ISSUE TITLE
Audioplayer: conflict with "selectlikeaboss" selection Firefox addon

### ISSUE THREAD

**Issue by Corak667** [os-js/OS.js#325] opened 2016-02-03 15:33 UTC
window::onerror()
Filename: chrome://selectlikeaboss/content/script.js
Line: 53:undefined
Message: IndexSizeError: Index or size is negative or greater than the allowed amount

**Comment by andersevenrud** [comment] 2016-02-03 15:36
How did you trigger this ? I've never heard or *selectlikeaboss*... what is it ?

**Comment by Corak667** [comment] 2016-02-03 15:38
@andersevenrud it's a Opera legacy styled methods of selections. 
https://addons.mozilla.org/ru/firefox/addon/select-like-a-boss/
Triggered just once (seems cannot repeat more)  in audioplayer when tried to scrolls/rewind some song. Maybe it can be triggered again. But inner bugreport window opened, so it wrote here.

**Comment by andersevenrud** [comment] 2016-02-03 16:34
> Triggered just once (seems cannot repeat more) in audioplayer when tried to scroll/rewind some song. 

Okay. This issue has been noted. There's a single-fire bug on the timeline scroll thing

**Comment by andersevenrud** [comment] 2016-02-03 16:34
Duplicate of #324

**Closed by andersevenrud** 2016-02-03 16:34 UTC
Labels: duplicate

**Comment by Corak667** [comment] 2016-02-03 16:37
@andersevenrud  nope, not duplicate.
The other are seems when session time was ended.

**Comment by MrSchism** [comment] 2016-02-03 16:44
I'm unable to reproduce.  Moreover, the behavior that plugin describes doesn't seem to differ from my default Firefox behavior.

Can you elaborate on what exactly it's supposed to as opposed to the default behavior?  This may help me be able to determine how to approach reproduction of the error.

**Comment by Corak667** [comment] 2016-02-03 17:21
Hm.. Yes. Seems duplicate still. Uploaded some music in Home:///Mus/ Dynamically added on player.  And tried to scroll. Got again
window::onerror()
Filename: http://osjsv2.0o.no/packages/default/MusicPlayer/combined.js
Line: 353:undefined
Message: InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
