### ISSUE TITLE
error: arduino yun setting

### ISSUE THREAD

**Issue by marketstr** [os-js/OS.js#673] opened 2018-03-08 01:21 UTC
An error occured while trying to launch: ApplicationArduinoSettings

> Application 'ApplicationArduinoSettings' preloading failed:  /packages/target/ArduinoSettings/combined.js?77925

**Comment by marktopper** [comment] 2018-03-09 09:02
Properly a duplicate of #625

**Comment by andersevenrud** [comment] 2018-03-09 10:55
Hi,

All of the issues you are reporting comes from the same problem. Some boards have some issues with networking (connection dropout).

Try using Luci instead: http://arduino-ip/cgi-bin/luci if you want to configure the board if the problem perists (even after upgrade).

Reference issue: #436

**Closed by andersevenrud** 2018-03-09 10:55 UTC
