### ISSUE TITLE
Google Drive cannot be accessed - 405

### ISSUE THREAD

**Issue by Corak667** [os-js/OS.js#322] opened 2016-02-03 14:00 UTC
Проихошла непредвиденная ошибка, возможно баг.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

**Comment by andersevenrud** [comment] 2016-02-03 14:25
Duplicate of #185

**Closed by andersevenrud** 2016-02-03 14:25 UTC
Labels: duplicate
