### ISSUE TITLE
error : arduino yun device setting

### ISSUE THREAD

**Issue by marketstr** [os-js/OS.js#674] opened 2018-03-08 01:23 UTC
An error occured while trying to launch: ApplicationArduinoSettings

> Application 'ApplicationArduinoSettings' preloading failed:  /packages/target/ArduinoSettings/combined.js?63890

**Comment by andersevenrud** [comment] 2018-03-09 10:55
Duplicate of #673

**Closed by andersevenrud** 2018-03-09 10:55 UTC
