### ISSUE TITLE
tian error

### ISSUE THREAD

**Issue by graffiti4u** [os-js/OS.js#440] opened 2016-07-10 14:01 UTC
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot convert undefined or null to object
    at http://arduino.local/packages/target/ArduinoService/combined.js?16356:98:16
    at http://arduino.local/packages/target/ArduinoService/combined.js?16356:191:7
    at http://arduino.local/packages/target/ArduinoService/combined.js?16356:264:7
    at _Handler.<anonymous> (http://arduino.local/osjs.js:1756:7)
    at Object.onerror (http://arduino.local/osjs.js:9466:17)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1266:16)
```

**Comment by andersevenrud** [comment] 2016-07-10 14:05
Duplicate of #438 

You have already submitted this problem twice. Make a comment in the old ones instead of making duplicates

**Closed by andersevenrud** 2016-07-10 14:05 UTC
Labels: duplicate
