### ISSUE TITLE
[VFS] No method 'access'

### ISSUE THREAD

**Issue by msaqibansari** [os-js/OS.js#460] opened 2016-08-11 12:58 UTC
/home/ubuntu/OSjs/src/server/node/core/vfs.js

i debug this issue and found something. Following code i picked from the file and seems you're passing fs and node_fs_extra module as wrong parameters location, you need to exchange them. If you see this code "(function(_path, _nfs, _fs) {" _nfs for node_fs_extra and _fs for fs but you're passing fs parameter as _nfs and node_fs_parameter as _fs.

```
(function(_path, _nfs, _fs) {

})(
  require('path'),
  require('fs'),
  require('node-fs-extra')
);
```

## Expected behaviour
copy file to new location

## Actual behaviour
```
UNCAUGHT EXCEPTION [TypeError: Object #<Object> has no method 'access'] TypeError: Object #<Object> has no method 'access'
    at /home/ubuntu/OSjs/src/server/node/core/vfs.js:428:17
    at Object.cb [as oncomplete] (fs.js:168:19)
```

## Steps to reproduce the error

```
  IconViewShortcutDialog.prototype.applySettings = function() {
    this.item.data.launch = this.scheme.find(this, 'InputShortcutLaunch').get('value');
    this.item.data.label = this.scheme.find(this, 'InputShortcutLabel').get('value');
    this.item.data.args = JSON.parse(this.scheme.find(this, 'InputTooltipFormatString').get('value') || null);

		// check if its folder shortcut then also rename its original folder
		if (this.item.data.launch == 'ApplicationFileManager' && Object.keys(this.item.data.args).length > 0) {
			var oldPath = this.item.data.args.path;
			var newPath = 'home:///'+this.item.data.label;

			this.item.data.args.path = newPath;
			OSjs.VFS.move(oldPath, newPath,function(error, result){
				console.log(error);
				console.log(result);
			});
		}
  };
```

**Comment by andersevenrud** [comment] 2016-08-11 13:23
Hi.

Thanks for reporting :)

I will investegate this when I get back home later today.

-- Anders

**Comment by andersevenrud** [comment] 2016-08-13 18:20
Are you running an outdated version of OS.js ? Your file (according to exception) does not match up with mine. Also, I'm not able to reproduce this, ex:

```OSjs.VFS.move('home:///3.tst', 'home:///3-2.tst', function(e,r) { console.warn(e,r); })```

Returns: `false true`.

Is the path you're building valid (`newPath`) ?

Also make sure to have latest dependencies, Do `npm install --production`. The library in use is `node-fs-extra` which has the `access` method exposed.

You can debug the fs library yourself by adding this in the OS.js root and run it via `node test.js`:

```var fs = require('node-fs-extra');
console.log(fs.access);```

```[Function]
```

**Comment by andersevenrud** [comment] 2016-08-29 16:41
I'm closing this issue now. If you feel it is unresolved, feel free to re-open.

**Closed by andersevenrud** 2016-08-29 16:41 UTC
Labels: possible bug
