### ISSUE TITLE
[Translations] missing arguments in  locales/xx_XX 

### ISSUE THREAD

**Issue by pringles49** [os-js/OS.js#369] opened 2016-04-11 18:49 UTC
## Expected behaviour
>Sorry for my english

> File View >  Affichage des fichiers
File View Options > Option d'affichage des fichiers
Enable TouchMenu > Activer le TouchMenu
invert Text Color > Inverser la couleur du texte
Desktop color snapping > ?
Windows Snapping > ?
appearance > apparence

## Actual behaviour

![traduction](https://cloud.githubusercontent.com/assets/18288140/14434863/704d8bbe-0015-11e6-8915-4a6df2675718.jpg)

## Steps to reproduce the error
open settings applications go to any tab ( in french translations mode )
## (Optinal) Browser and OS information
>google chrome , mac os x el capitan

## I think
> this bug is  in all  locales/xx_XX files and is due to missing arguments  for some text 
and missing declation of this arguments in : 
[https://github.com/os-js/OS.js/blob/master/src/packages/default/Settings/scheme.html](url) 

ideas to complete xx_XX (french) file 😄 
```
'LBL_DESKTOP' : 'Bureau'
'LBL_FILEVIEW' : 'Affichage des fichiers'
'LBL_FILEVIEW_OPTION' : 'Option d'affichage des fichiers'
'LBL_GROUPS' : 'Groupes'
'LBL_ID'  : 'ID'
'LBL_AUTO_HIDE' : 'Masquage automatique '
```

and missing argument in scheme.html who existe in xx_XX 
```
LBL_LOCALES'    <gui-tab-container data-id="TabUserLang" data-label="Locales">
LBL_NAME'        <gui-label>Name</gui-label>
LBL_USERNAME   <gui-label>Username</gui-label>
LBL_ICONVIEW <gui-tab-container data-id="TabIconView" data-label="Icon View">

```

### I just want to be sur its a bug/missing Translations  i will make the change if needed

**Comment by andersevenrud** [comment] 2016-04-11 18:57
This is not a bug, but simply:

1. Some translations are not up-to-date with source/applications
2. Some applications (like settings) have not correct labels set

If you want to get a list of missing "keys", do this in your browser console:

```
Object.keys(OSjs.Locales.en_EN).filter(function(v) {
  return typeof OSjs.Locales.fr_FR[v] === 'undefined';
});
```

So yes, these are *missing translations* :)

If you want to look into it, please go ahead.

**Comment by andersevenrud** [comment] 2016-04-11 18:58
Ref: #18

**Comment by pringles49** [comment] 2016-04-11 19:03
thanks I will look into it 😄

**Comment by andersevenrud** [comment] 2016-04-11 19:22
FYI, if your plan was to make a pull-request or something, please read this before you start commiting and pushing changes: https://github.com/os-js/OS.js/blob/master/CONTRIBUTING.md

:)

**Comment by andersevenrud** [comment] 2016-04-11 19:24
Shortcut: https://os.js.org/doc/manuals/man-development.html

Scroll to "How to contribute"

**Comment by pringles49** [comment] 2016-04-11 22:59
#370

**Comment by andersevenrud** [comment] 2016-04-12 20:41
Closing this, because #370 was merged

**Closed by andersevenrud** 2016-04-12 20:41 UTC
Labels: locale, question
