### ISSUE TITLE
tian error

### ISSUE THREAD

**Issue by graffiti4u** [os-js/OS.js#441] opened 2016-07-10 14:51 UTC
An error occured while trying to launch: ApplicationArduinoPackageManager

> Application 'ApplicationArduinoPackageManager' preloading failed:  /packages/target/ArduinoPackageManager/combined.js?37584

**Comment by andersevenrud** [comment] 2016-07-10 14:53
Duplicate of #436, ref: #437

**Closed by andersevenrud** 2016-07-10 14:53 UTC
Labels: duplicate
